# Generated by Django 5.2.1 on 2025-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_doc_ai_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="Text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
